### ISSUE TITLE
sqlite3.OperationalError: no such table: CUPTI_ACTIVITY_KIND_CDP_KERNEL

### ISSUE THREAD

**Issue by dmenig** [rossumai/nvprof-tools#3]
Just installed nvprof and ran this : 
``nvprof_tools slice foo.sqlite -s 1.0 -e 10.0``

and I got this error. 

```
Traceback (most recent call last):
  File "/home/damien/.local/bin/nvprof_tools", line 11, in <module>
    sys.exit(main())
  File "/home/damien/.local/lib/python3.6/site-packages/nvprof/__main__.py", line 41, in main
    cmd_slice(args.db_file, args.start, args.end)
  File "/home/damien/.local/lib/python3.6/site-packages/nvprof/__main__.py", line 15, in cmd_slice
    nvprof.with_conn(db_file, slice_events)
  File "/home/damien/.local/lib/python3.6/site-packages/nvprof/__init__.py", line 133, in with_conn
    func(conn)
  File "/home/damien/.local/lib/python3.6/site-packages/nvprof/__main__.py", line 14, in slice_events
    nvprof.slice_events(conn, int(start_sec * 1e9), int(end_sec * 1e9))
  File "/home/damien/.local/lib/python3.6/site-packages/nvprof/__init__.py", line 121, in slice_events
    base_time, _ = time_range(conn)
  File "/home/damien/.local/lib/python3.6/site-packages/nvprof/__init__.py", line 39, in time_range
    c.execute('SELECT MIN(start), MAX(end) FROM {}'.format(table))
sqlite3.OperationalError: no such table: CUPTI_ACTIVITY_KIND_CDP_KERNEL

```

**Comment by bzamecnik** [comment]
Aah, possibly some CUDA version mismatch (the tables may have changed)...
